services:
  iotnet-ns3:
    container_name: iotnet-ns3
    build: ./ns3
    volumes:
      - ./ns3/iotnet:/root/ns-allinone-3.40/ns-3.40/contrib/iotnet
      - ./ns3/output:/root/ns-allinone-3.40/ns-3.40/output
    links:
      - server-node
  server-node:
    container_name: server-node
    build: ./node
    volumes:
      - ./node/server:/root/app
