services:
  iotnet-ns3:
    container_name: iotnet-ns3
    build: ./ns3
    volumes:
      - ./ns3/wifi:/root/ns-allinone-3.30.1/ns-3.30.1/src/wifi
      - ./ns3/jamming:/root/ns-allinone-3.30.1/ns-3.30.1/src/jamming
      - ./ns3/iotnet:/root/ns-allinone-3.30.1/ns-3.30.1/src/iotnet
      - ./ns3/output:/root/ns-allinone-3.30.1/ns-3.30.1/output
    links:
      - server-node
    depends_on:
      - server-node
      - ml-server
  server-node:
    container_name: server-node
    build: ./next-app
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./next-app:/root/app
    links:
      - ml-server
    depends_on:
      - ml-server
  ml-server:
    container_name: ml-server
    build: ./mlserver
    volumes:
      - ./mlserver:/root/mlserver
    ports:
      - 5000:5000
